//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salao
{
    using System;
    using System.Collections.Generic;
    
    public partial class agenda
    {
        public int IdAgenda { get; set; }
        public string NomeCliente { get; set; }
        public Nullable<System.DateTime> DataAgenda { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
    
        public virtual funcionario funcionario { get; set; }
    }
}
