//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class salaoEntities : DbContext
    {
        public salaoEntities()
            : base("name=salaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agenda> agenda { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
    }
}
